package dbtarzan.localization

class English extends Localization {
    def settings = "Settings"
    def globalSettings = "Global Settings"
    def editConnections = "Edit Connections"    
    def help = "Help"      
    def documentation = "Documentation"      
    def new_ = "New"
    def remove = "Remove"
    def duplicate = "Duplicate"
    def cancel = "Cancel"
    def save = "Save"
    def name = "Name"
    def user = "User"
    def password = "Password"
    def schema = "Schema"
    def delimiters = "Delimiters"
    def maxRows = "Max Rows"
    def tables = "Tables"
    def databases = "Databases"
    def foreignKeys = "Foreign keys"
    def connectionReset = "Connection Reset"
    def more= "More..."
    def copySQLToClipboard = "Copy SQL To Clipboard"
    def closeTabsBeforeThis = "Close tabs before this"
    def closeTabsAfterThis = "Close tabs after this"
    def closeAllTabs = "Close all tabs"
    def checkAll = "Check All"
    def uncheckAll = "Uncheck All"
    def rowDetails = "Row Details"
}