package dbtarzan.localization

class Italian extends Localization {
    def settings = "Opzioni"
    def globalSettings = "Opzioni Globali"
    def editConnections = "Modifica Connessioni"  
    def help = "Aiuto"      
    def documentation = "Documentazione"
    def new_ = "Nuovo"
    def remove = "Cancella"
    def duplicate = "Duplica"
    def cancel = "Annulla"
    def save = "Salva"
    def name = "Nome"
    def user = "Utente"
    def password = "Password"
    def schema = "Schema"
    def delimiters = "Separatori"
    def maxRows = "Max Righe"    
    def tables = "Tabelle"    
    def databases = "Database"
    def foreignKeys = "Chiavi esterne"
    def connectionReset = "Resetta connessione"
    def more = "Altro..."
    def language = "Lingua"
    def editGlobalSettings = "Modifica Opzioni Globali"    
    def copySQLToClipboard = "Copia SQL nel Clipboard"
    def closeTabsBeforeThis = "Chiudi le tab prima di questa"
    def closeTabsAfterThis = "Chiudi le tab dopo questa"
    def closeAllTabs = "Chiudi tutte le tab"
    def checkAll = "Spunta Tutto"
    def uncheckAll = "Rimuovi tutte le spunte"
    def rowDetails = "Dettagli della riga"  
    def areYouSureClose = "Sicuro di chiudere senza salvare?"
    def areYouSureSaveConnections = "Sicuro di voler salvare le connessioni?"
    def saveConnections = "Salva le connessioni"
    def areYouSureSaveGlobalSettings = "Sicuro di voler salvare le opzioni globali?"    
    def saveGlobalSettings = "Salvare le opzioni globali"
}